options:
  logging: LEGACY
  pool: {}
projectId: jscma-gcf-test
steps:
- args:
  - rebase
  - us-central1-docker.pkg.dev/jscma-gcf-test/app-repos/rebase-app
  - --run-image
  - gcr.io/buildpacks/google-22/run:latest
  - --publish
  entrypoint: pack
  name: gcr.io/k8s-skaffold/pack