options:
  logging: LEGACY
  pool: {}
projectId: jscma-gcf-test
steps:
- name: rebase
- args:
  - rebase
  - --run-image 
  - gcr.io/buildpacks/builder:google-22
  - --publish
  entrypoint: pack
  name: gcr.io/k8s-skaffold/pack