options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: $PROJECT_ID
steps:
- name: gcr.io/k8s-skaffold/pack
  entrypoint: pack
  args:
  - build
  - us-central1-docker.pkg.dev/$PROJECT_ID/app-repos/gcp-buildpack-fast-app
  - --builder
  - gcr.io/buildpacks/builder:latest
  - --cache-image
  - us-central1-docker.pkg.dev/$PROJECT_ID/app-repos/gcp-buildpack-cache-test:latest
  - --publish 