options:
  logging: LEGACY
  pool: {}
projectId: jscma-gcf-test
steps:
- name: gcr.io/k8s-skaffold/pack
  entrypoint: pack
  args:
  - rebase
  - us-central1-docker.pkg.dev/jscma-gcf-test/app-repos/rebase-app
  - --run-image
  - gcr.io/buildpacks/google-22/run:latest
  - --publish
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'rebase-app'
   - '--image'
   - us-central1-docker.pkg.dev/jscma-gcf-test/app-repos/rebase-app
   - '--region'
   - us-east1