options:
  logging: LEGACY
  pool: {}
projectId: jscma-gcf-test
steps:
- args:
  - rebase
  - us-east1-docker.pkg.dev/jscma-gcf-test/cloud-run-source-deploy/rebase-app
  - --run-image
  - gcr.io/buildpacks/gcp/run:latest
  - --publish
  entrypoint: pack
  name: gcr.io/k8s-skaffold/pack